# Generated by Django 4.0 on 2022-01-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroexpediente',
            name='numNue',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
