# Generated by Django 4.0 on 2022-01-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Expedientes', '0002_alter_registroexpediente_numnue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroexpediente',
            name='numNue',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
