# Generated by Django 3.2.11 on 2022-03-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expedientes', '0003_alter_registroexpediente_numnue'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroexpediente',
            name='expedientePDF',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
