# Generated by Django 3.2.11 on 2022-03-13 03:02

import Expedientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expedientes', '0004_registroexpediente_expedientepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroexpediente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='registroexpediente',
            name='expedientePDF',
            field=models.FileField(default=None, null=True, upload_to=Expedientes.models.content_file_name),
        ),
    ]
